package me.diamondman121314.Slimedustry;

import me.mrCookieSlime.Slimefun.cscorelib2.item.CustomItem;
import me.mrCookieSlime.Slimefun.Lists.Categories;
import me.mrCookieSlime.Slimefun.Lists.RecipeType;
import me.mrCookieSlime.Slimefun.Lists.SlimefunItems;
import me.mrCookieSlime.Slimefun.Objects.Category;
import me.mrCookieSlime.Slimefun.Objects.Research;
import me.mrCookieSlime.Slimefun.Objects.SlimefunItem.ChargableItem;
import me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem;
import me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunMachine;
import me.mrCookieSlime.Slimefun.api.Slimefun;
import me.mrCookieSlime.Slimefun.api.SlimefunItemStack;
import org.bukkit.Color;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.block.BlockFace;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;


public class Setup {
    public static SlimefunMachine iwMachine;
    public static SlimefunMachine pbMachine;
    public static SlimefunMachine mfMachine;
    static RecipeType iwType;
    static RecipeType pbType;
    static RecipeType mfType;
    static RecipeType ldType;
    static Category Slimedustry;
    static Category Dusts;
    static Category Plates;
    static Category Ingots;
    static SlimefunItemStack iw;
    static SlimefunItemStack tank;
    static SlimefunItemStack rg;
    static SlimefunItemStack pb;
    static SlimefunItemStack ml;
    static SlimefunItemStack rubber;
    static SlimefunItemStack nuke;
    static SlimefunItemStack sr;
    static SlimefunItemStack rap;
    static SlimefunItemStack sb;
    static SlimefunItemStack mf;
    static SlimefunItemStack uu;
    static SlimefunItemStack ti;
    static SlimefunItemStack td;
    static SlimefunItemStack rc;
    static SlimefunItemStack io;
    static SlimefunItemStack ip;
    static SlimefunItemStack nh;
    static SlimefunItemStack nc;
    static SlimefunItemStack nl;
    static SlimefunItemStack nb;
    static SlimefunItemStack it;
    static SlimefunItemStack rb;
    static SlimefunItemStack cv;
    static SlimefunItemStack rg7;
    static SlimefunItemStack uu3;
    static SlimefunItemStack td2;

    public static void setupMisc(Slimedustry main) {
        Slimedustry = new Category(new NamespacedKey(main, "slimedustry"), new CustomItem(Material.BEACON, "&7Slimedustry"));
        Dusts = new Category(new NamespacedKey(main, "dusts"), new CustomItem(Material.SUGAR, "&7Dusts"));
        Plates = new Category(new NamespacedKey(main, "plates"), new CustomItem(Material.MAP, "&7Plates"));
        Ingots = new Category(new NamespacedKey(main, "ingots"), new CustomItem(Material.IRON_INGOT, "&7Ingots"));

        iwType = new RecipeType(new NamespacedKey(main, "industrial_crafting_table_material"), new CustomItem(Material.CRAFTING_TABLE, "&bIndustrial Crafting Table", "", "&a&oCraft it in an Industrial Crafting Table"));
        pbType = new RecipeType(new NamespacedKey(main, "plate_bender_material"), new CustomItem(Material.PISTON, "&bPlate Bender", "", "&a&oBend it in a Plate Bender"));
        mfType = new RecipeType(new NamespacedKey(main, "mass_fabricator_material"), new CustomItem(Material.BEACON, "&9&lMass Fabricator", "", "&a&oFabricate it using a Mass Fabricator"));
        ldType = new RecipeType(new NamespacedKey(main, "leaves_decay_material"), new CustomItem(Material.OAK_LEAVES, "&bLeaves Decay", "", "&aObtain this item when Leaves decay (can be any leaves)"));
    }

    public static void setupItems(Slimedustry main) {
        iw = new SlimefunItemStack("INDUSTRIAL_WORKBENCH", Material.CRAFTING_TABLE, "&bIndustrial Crafting Table", "", "&a&oUsed for Industrial Crafting");
        pb = new SlimefunItemStack("PLATE_BENDER", Material.PISTON, "&bPlate Bender", "", "&a&oCan bend Ingots into Plates");
        mf = new SlimefunItemStack("MASS_FABRICATOR", Material.BEACON, "&9&lMass Fabricator", "", "&a&oGenerates UU-Matter");
        tank = new SlimefunItemStack("TANK", Material.WHITE_STAINED_GLASS, "&6Tank", "", "&a&oStores Liquids");
        rg = new SlimefunItemStack("REINFORCED_GLASS", Material.GLASS, "&bReinforced Glass");
        //rg7 = new CustomItem(Material.GLASS, "Glass", 0, 7, null);
        ml = new SlimefunItemStack("MINING_LASER", Material.DIAMOND_HORSE_ARMOR, "&bMining Laser", "&6Mode: &1Mining", "&7Charge: &b0.0 J", "&7Capacity: &b40.0 J", "&a&oRight click to shoot, left click to change mode");
        rubber = new SlimefunItemStack("RUBBER", Material.LEATHER, "&bRubber");
        nuke = new SlimefunItemStack("NUKE", Material.TNT, "&4Nuke", "&cAre you sure this is a good idea?", "&3Automatically detonates on placement");
        sr = new SlimefunItemStack("STICKY_RESIN", Material.CLAY_BALL, "&bSticky Resin");
        rap = new SlimefunItemStack("REINFORCED_ALLOY_PLATE", Material.PAPER, "&bReinforced Alloy Plate");
        sb = new SlimefunItemStack("STATIC_BOOTS", Material.LEATHER_BOOTS, Color.BLACK, "&6Static Boots", "", "&a&oCharges the item in your hand while you walk");
        uu = new SlimefunItemStack("UU-MATTER", Material.INK_SAC, "&dUU-Matter");
        //uu3 = new CustomItem(uu), 3);
        ti = new SlimefunItemStack("TITANIUM_INGOT", Material.IRON_INGOT, "&bTitanium Ingot");
        td = new SlimefunItemStack("TITANIUM_DUST", Material.SUGAR, "&6Titanium Dust");
        //td2 = (ItemStack)new CustomItem(Material.SUGAR, "Dust", 0, 2, null);
        rc = new SlimefunItemStack("ROCK_CUTTER", Material.DIAMOND_PICKAXE, "&bRock Cutter", "", "&7Charge: &b0.0 J", "&7Capacity: &b100.0 J");
        rc.addEnchantment(Enchantment.SILK_TOUCH, 1);
        io = new SlimefunItemStack("IRIDIUM_ORE", Material.GHAST_TEAR, "&f&lIridium Ore");
        ip = new SlimefunItemStack("IRIDIUM_PLATE", Material.PAPER, "&f&lIridium Plate");
        nh = new SlimefunItemStack("NANO_HELMET", Material.LEATHER_HELMET, Color.BLACK, "&8&lNanoSuit Helmet", "&a&oNightVision included!", "&7Charge: &b0.0 J", "&7Capacity: &b1000.0 J");
        nc = new SlimefunItemStack("NANO_CHESTPLATE", Material.LEATHER_CHESTPLATE, Color.BLACK, "&8&lNanoSuit Chestplate", "", "&7Charge: &b0.0 J", "&7Capacity: &b1000.0 J");
        nl = new SlimefunItemStack("NANO_LEGGINGS", Material.LEATHER_LEGGINGS, Color.BLACK, "&8&lNanoSuit Leggings", "", "&7Charge: &b0.0 J", "&7Capacity: &b1000.0 J");
        nb = new SlimefunItemStack("NANO_BOOTS", Material.LEATHER_BOOTS, Color.BLACK, "&8&lNanoSuit Boots", "", "&7Charge: &b0.0 J", "&7Capacity: &b1000.0 J");
        it = new SlimefunItemStack("IMPURE_TITANIUM", Material.GUNPOWDER, "&bImpure Titanium Dust");
        rb = new SlimefunItemStack("SD_RUBBER_BOOTS", Material.LEATHER_BOOTS, Color.BLACK, "&6Rubber Boots", "&a&oPrevents Fall Damage");
        cv = new SlimefunItemStack("COMPOSITE_VEST", Material.IRON_CHESTPLATE, "&7Composite Vest");
        cv.addUnsafeEnchantment(Enchantment.DURABILITY, 5);

        iwMachine = new SlimefunMachine(Slimedustry, iw, new ItemStack[] {null, new ItemStack(Material.HEAVY_WEIGHTED_PRESSURE_PLATE), null, null, new ItemStack(Material.DISPENSER), null, null, new ItemStack(Material.CRAFTING_TABLE), null}, new ItemStack[0], BlockFace.SELF);
        SlimefunItem tankItem = new SlimefunItem(Slimedustry, tank, RecipeType.MULTIBLOCK, new ItemStack[] {null, null, null, null, new ItemStack(Material.WHITE_STAINED_GLASS), null, null, new CustomItem(Material.DISPENSER, "&r&oDispenser (Facing Up)"), null});
        SlimefunItem rgItem = new SlimefunItem(Slimedustry, rg, iwType, new ItemStack[] {new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), rap, new ItemStack(Material.GLASS), rap, new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS)});
        pbMachine = new SlimefunMachine(Slimedustry, pb, new ItemStack[] {null, null, null, null, new ItemStack(Material.PISTON), null, null, new CustomItem(Material.DISPENSER, "&r&oDispenser (Facing Up)"), null}, /*new ItemStack[] {SlimefunItems.STEEL_INGOT, SlimefunItems.STEEL_PLATE, SlimefunItems.REINFORCED_ALLOY_INGOT, rap}, */new ItemStack[0], BlockFace.SELF);
        ChargableItem mlItem = new ChargableItem(Categories.TECH, ml, iwType, new ItemStack[] {new ItemStack(Material.REDSTONE), SlimefunItems.POWER_CRYSTAL, SlimefunItems.POWER_CRYSTAL, rap, rap, SlimefunItems.ADVANCED_CIRCUIT_BOARD, null, rap, rap});
        SlimefunItem rubberItem = new SlimefunItem(Categories.RESOURCES, rubber, RecipeType.SMELTERY, new ItemStack[] {sr, null, null, null, null, null, null, null, null});
        SlimefunItem nukeItem = new SlimefunItem(Slimedustry, nuke, iwType, new ItemStack[] {new ItemStack(Material.GUNPOWDER), SlimefunItems.URANIUM, new ItemStack(Material.GUNPOWDER), SlimefunItems.URANIUM, new ItemStack(Material.GUNPOWDER), SlimefunItems.URANIUM, new ItemStack(Material.GUNPOWDER), SlimefunItems.URANIUM, new ItemStack(Material.GUNPOWDER)});
        SlimefunItem srItem = new SlimefunItem(Categories.MISC, sr, ldType, new ItemStack[] {null, null, null, null, new ItemStack(Material.OAK_LEAVES), null, null, null, null});
        SlimefunItem rapItem = new SlimefunItem(Plates, rap, pbType, new ItemStack[] {null, null, null, null, SlimefunItems.REINFORCED_ALLOY_INGOT, null, null, null, null});
        SlimefunItem sbItem = new SlimefunItem(Categories.TECH, sb, iwType, new ItemStack[] {null, new ItemStack(Material.IRON_BOOTS), null, null, new ItemStack(Material.WHITE_WOOL), null, rubber, rubber, rubber});
        mfMachine = new SlimefunMachine(Slimedustry, mf, new ItemStack[] {null, new ItemStack(Material.LIGHT_WEIGHTED_PRESSURE_PLATE), null, new ItemStack(Material.IRON_BLOCK), new ItemStack(Material.DISPENSER), new ItemStack(Material.IRON_BLOCK), null, new ItemStack(Material.BEACON), null}, /*new ItemStack[] {SlimefunItems.POWER_CRYSTAL, uu}, */new ItemStack[0], BlockFace.SELF);
        SlimefunItem uuItem = new SlimefunItem(Categories.RESOURCES, uu, mfType, new ItemStack[] {null, null, null, null, SlimefunItems.POWER_CRYSTAL, null, null, null, null});
        //SlimefunItem uu3Item = new SlimefunItem(Categories.RESOURCES, uu3, mfType, new ItemStack[] {null, null, null, null, SlimefunItems.POWER_CRYSTAL, null, null, null, null}, new CustomItem(uu3, 3));
        SlimefunItem tiItem = new SlimefunItem(Ingots, ti, RecipeType.SMELTERY, new ItemStack[] {td, null, null, null, null, null, null, null, null});
        SlimefunItem tdItem = new SlimefunItem(Dusts, td, iwType, new ItemStack[] {it, it, it, it, new ItemStack(Material.WATER_BUCKET), it, it, it, it});
        ChargableItem rcItem = new ChargableItem(Categories.TECH, rc, iwType, new ItemStack[] {new ItemStack(Material.DIAMOND), ti, null, new ItemStack(Material.DIAMOND), ti, null, new ItemStack(Material.DIAMOND), SlimefunItems.BASIC_CIRCUIT_BOARD, SlimefunItems.BATTERY});
        SlimefunItem ioItem = new SlimefunItem(Categories.RESOURCES, io, iwType, new ItemStack[] {uu, uu, uu, null, uu, null, uu, uu, uu});
        SlimefunItem ipItem = new SlimefunItem(Plates, ip, iwType, new ItemStack[] {io, rap, io, rap, new ItemStack(Material.DIAMOND), rap, io, rap, io});
        ChargableItem nhItem = new ChargableItem(Categories.ARMOR, nh, RecipeType.ARMOR_FORGE, new ItemStack[] {SlimefunItems.CARBON, SlimefunItems.POWER_CRYSTAL, SlimefunItems.CARBON, SlimefunItems.CARBON, SlimefunItems.NIGHT_VISION_GOGGLES, SlimefunItems.CARBON, null, null, null});
        ChargableItem ncItem = new ChargableItem(Categories.ARMOR, nc, RecipeType.ARMOR_FORGE, new ItemStack[] {SlimefunItems.CARBON, null, SlimefunItems.CARBON, SlimefunItems.CARBON, SlimefunItems.POWER_CRYSTAL, SlimefunItems.CARBON, SlimefunItems.CARBON, SlimefunItems.CARBON, SlimefunItems.CARBON});
        ChargableItem nlItem = new ChargableItem(Categories.ARMOR, nl, RecipeType.ARMOR_FORGE, new ItemStack[] {SlimefunItems.CARBON, SlimefunItems.POWER_CRYSTAL, SlimefunItems.CARBON, SlimefunItems.CARBON, null, SlimefunItems.CARBON, SlimefunItems.CARBON, null, SlimefunItems.CARBON});
        ChargableItem nbItem = new ChargableItem(Categories.ARMOR, nb, RecipeType.ARMOR_FORGE, new ItemStack[] {null, null, null, SlimefunItems.CARBON, null, SlimefunItems.CARBON, SlimefunItems.CARBON, SlimefunItems.POWER_CRYSTAL, SlimefunItems.CARBON});
        SlimefunItem itItem = new SlimefunItem(Dusts, it, RecipeType.ORE_WASHER, new ItemStack[] {SlimefunItems.SIFTED_ORE, null, null, null, null, null, null, null, null});
        SlimefunItem rbItem = new SlimefunItem(Categories.TECH, rb, iwType, new ItemStack[] {null, null, null, rubber, null, rubber, rubber, new ItemStack(Material.SLIME_BLOCK), rubber});
        SlimefunItem cvItem = new SlimefunItem(Categories.ARMOR, cv, RecipeType.ARMOR_FORGE, new ItemStack[] {rap, null, rap, rap, new ItemStack(Material.IRON_CHESTPLATE), rap, rap, new ItemStack(Material.LEATHER_CHESTPLATE), rap});

        //mfMachine.addRecipe(uuItem.getRecipe(), uu3);
        mfMachine.addRecipe(uuItem.getRecipe(), uu);
        //iwMachine.addRecipe(rgItem.getRecipe(), rg7);
        iwMachine.addRecipe(rgItem.getRecipe(), rg);
        iwMachine.addRecipe(mlItem.getRecipe(), ml);
        iwMachine.addRecipe(rcItem.getRecipe(), rc);
        iwMachine.addRecipe(sbItem.getRecipe(), sb);
        iwMachine.addRecipe(ioItem.getRecipe(), io);
        iwMachine.addRecipe(ipItem.getRecipe(), ip);
        //iwMachine.addRecipe(tdItem.getRecipe(), td2);
        iwMachine.addRecipe(tdItem.getRecipe(), td);
        iwMachine.addRecipe(rbItem.getRecipe(), rb);
        //mfMachine.addRecipe(new ItemStack[] {null, null, null, null, null, null, null, SlimefunItems.POWER_CRYSTAL, null}, SlimefunItem.getByItem(uu) );
        iwMachine.addRecipe(new ItemStack[] {rubber, rubber, rubber, new ItemStack(Material.REDSTONE), new ItemStack(Material.IRON_INGOT), new ItemStack(Material.REDSTONE), rubber, rubber, rubber}, SlimefunItems.BASIC_CIRCUIT_BOARD);
        iwMachine.addRecipe(new ItemStack[] {new ItemStack(Material.REDSTONE), new ItemStack(Material.GLOWSTONE_DUST), new ItemStack(Material.REDSTONE), new ItemStack(Material.INK_SAC), SlimefunItems.BASIC_CIRCUIT_BOARD, new ItemStack(Material.INK_SAC), new ItemStack(Material.REDSTONE), new ItemStack(Material.GLOWSTONE_DUST), new ItemStack(Material.REDSTONE)}, SlimefunItems.ADVANCED_CIRCUIT_BOARD);
        iwMachine.addRecipe(new ItemStack[] {new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.BLACK_WOOL), rg, new ItemStack(Material.BLACK_WOOL), null, null, null}, SlimefunItems.SCUBA_HELMET);
        iwMachine.addRecipe(new ItemStack[] {new ItemStack(Material.COAL_BLOCK), new ItemStack(Material.COAL_BLOCK), new ItemStack(Material.COAL_BLOCK), rg, new ItemStack(Material.COAL_BLOCK), rg, new ItemStack(Material.COAL_BLOCK), null, new ItemStack(Material.COAL_BLOCK)}, SlimefunItems.NIGHT_VISION_GOGGLES);
        iwMachine.addRecipe(SlimefunItem.getByID("BATTERY").getRecipe(), SlimefunItems.BATTERY);
        iwMachine.addRecipe(SlimefunItem.getByID("STEEL_THRUSTER").getRecipe(), SlimefunItems.STEEL_THRUSTER);
        iwMachine.addRecipe(SlimefunItem.getByID("POWER_CRYSTAL").getRecipe(), SlimefunItems.POWER_CRYSTAL);
        iwMachine.addRecipe(SlimefunItem.getByID("DURALUMIN_JETPACK").getRecipe(), SlimefunItems.DURALUMIN_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("DURALUMIN_MULTI_TOOL").getRecipe(), SlimefunItems.DURALUMIN_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("DURALUMIN_JETBOOTS").getRecipe(), SlimefunItems.DURALUMIN_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("SOLDER_JETPACK").getRecipe(), SlimefunItems.SOLDER_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("SOLDER_MULTI_TOOL").getRecipe(), SlimefunItems.SOLDER_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("SOLDER_JETBOOTS").getRecipe(), SlimefunItems.SOLDER_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("BILLON_JETPACK").getRecipe(), SlimefunItems.BILLON_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("BILLON_MULTI_TOOL").getRecipe(), SlimefunItems.BILLON_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("BILLON_JETBOOTS").getRecipe(), SlimefunItems.BILLON_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("STEEL_JETPACK").getRecipe(), SlimefunItems.STEEL_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("STEEL_MULTI_TOOL").getRecipe(), SlimefunItems.STEEL_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("STEEL_JETBOOTS").getRecipe(), SlimefunItems.STEEL_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("DAMASCUS_STEEL_JETPACK").getRecipe(), SlimefunItems.DAMASCUS_STEEL_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("DAMASCUS_STEEL_MULTI_TOOL").getRecipe(), SlimefunItems.DAMASCUS_STEEL_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("DAMASCUS_STEEL_JETBOOTS").getRecipe(), SlimefunItems.DAMASCUS_STEEL_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("REINFORCED_ALLOY_JETPACK").getRecipe(), SlimefunItems.REINFORCED_ALLOY_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("REINFORCED_ALLOY_MULTI_TOOL").getRecipe(), SlimefunItems.REINFORCED_ALLOY_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("REINFORCED_ALLOY_JETBOOTS").getRecipe(), SlimefunItems.REINFORCED_ALLOY_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("CARBONADO_JETPACK").getRecipe(), SlimefunItems.CARBONADO_JETPACK);
        iwMachine.addRecipe(SlimefunItem.getByID("CARBONADO_MULTI_TOOL").getRecipe(), SlimefunItems.CARBONADO_MULTI_TOOL);
        iwMachine.addRecipe(SlimefunItem.getByID("CARBONADO_JETBOOTS").getRecipe(), SlimefunItems.CARBONADO_JETBOOTS);
        iwMachine.addRecipe(SlimefunItem.getByID("PARACHUTE").getRecipe(), SlimefunItems.PARACHUTE);
        iwMachine.addRecipe(SlimefunItem.getByID("SOLAR_HELMET").getRecipe(), SlimefunItems.SOLAR_HELMET);
        iwMachine.addRecipe(SlimefunItem.getByID("ARMORED_JETBOOTS").getRecipe(), SlimefunItems.ARMORED_JETBOOTS);
        ((SlimefunMachine)SlimefunItem.getByID("ORE_WASHER")).addRecipe(new ItemStack[] {SlimefunItems.SIFTED_ORE}, it);

        iwMachine.register(main);
        tankItem.register(main);
        rgItem.register(main);
        pbMachine.register(main);
        mlItem.register(main);
        rubberItem.register(main);
        nukeItem.register(main);
        srItem.register(main);
        rapItem.register(main);
        sbItem.register(main);
        mfMachine.register(main);
        uuItem.register(main);
        tiItem.register(main);
        tdItem.register(main);
        rcItem.register(main);
        ioItem.register(main);
        ipItem.register(main);
        nhItem.register(main);
        ncItem.register(main);
        nlItem.register(main);
        nbItem.register(main);
        itItem.register(main);
        rbItem.register(main);
        cvItem.register(main);
    }

    public static void setupResearches(Slimedustry main) {
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "industrial_workbench"), 1001, "Industrial Crafting Table", 8), iw);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "tank"), 1002, "Liquid Storage", 7), tank);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "reinforced_glass"), 1003, "Reinforced Glass", 10), rg);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "plate_bender"), 1004, "Plate Bender", 12), pb);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "mining_laser"), 1005,"Mining Laser", 13), ml);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "nuke"), 1006, "Nuke", 15), nuke);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "sticky_situation"), 1007, "Sticky Situation", 5), sr);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "plates"), 1008, "Plates", 6), rap, ip);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "tech_boots"), 1009, "Tech Boots", 7), sb, rb);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "totally_worth_it"), 1010, "Totally Worth It", 18), mf);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "high-grade"), 1011, "High-Grade", 18), ti, td, it);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "cutting_the_rocks"), 1012, "Cutting The Rocks", 14), rc);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "iridium_ore"), 1013, "Iridium Ore", 15), io);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "nanosuit"), 1014, "NanoSuit", 13), nh, nc, nl, nb);
        Slimefun.registerResearch(new Research(new NamespacedKey(main, "tankin"), 1014, "Tankin'", 11), cv);
    }

    public static void changeRecipes() {
        SlimefunItem.getByID("BASIC_CIRCUIT_BOARD").setRecipe(new ItemStack[] {rubber, rubber, rubber, new ItemStack(Material.REDSTONE), new ItemStack(Material.IRON_INGOT), new ItemStack(Material.REDSTONE), rubber, rubber, rubber});
        SlimefunItem.getByID("BASIC_CIRCUIT_BOARD").setRecipeType(iwType);
        SlimefunItem.getByID("ADVANCED_CIRCUIT_BOARD").setRecipe(new ItemStack[] {new ItemStack(Material.REDSTONE), new ItemStack(Material.GLOWSTONE_DUST), new ItemStack(Material.REDSTONE), new ItemStack(Material.INK_SAC), SlimefunItems.BASIC_CIRCUIT_BOARD, new ItemStack(Material.INK_SAC), new ItemStack(Material.REDSTONE), new ItemStack(Material.GLOWSTONE_DUST), new ItemStack(Material.REDSTONE)});
        SlimefunItem.getByID("ADVANCED_CIRCUIT_BOARD").setRecipeType(iwType);
        SlimefunItem.getByID("STEEL_THRUSTER").setRecipeType(iwType);
        SlimefunItem.getByID("POWER_CRYSTAL").setRecipeType(iwType);
        SlimefunItem.getByID("BATTERY").setRecipeType(iwType);
        SlimefunItem.getByID("DURALUMIN_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("DURALUMIN_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("DURALUMIN_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("SOLDER_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("SOLDER_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("SOLDER_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("BILLON_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("BILLON_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("BILLON_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("STEEL_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("STEEL_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("STEEL_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("DAMASCUS_STEEL_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("DAMASCUS_STEEL_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("DAMASCUS_STEEL_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("REINFORCED_ALLOY_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("REINFORCED_ALLOY_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("REINFORCED_ALLOY_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("CARBONADO_JETPACK").setRecipeType(iwType);
        SlimefunItem.getByID("CARBONADO_MULTI_TOOL").setRecipeType(iwType);
        SlimefunItem.getByID("CARBONADO_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("PARACHUTE").setRecipeType(iwType);
        SlimefunItem.getByID("SOLAR_HELMET").setRecipeType(iwType);
        SlimefunItem.getByID("ARMORED_JETBOOTS").setRecipeType(iwType);
        SlimefunItem.getByID("SCUBA_HELMET").setRecipe(new ItemStack[] {new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.ORANGE_WOOL), new ItemStack(Material.BLACK_WOOL), new CustomItem(Material.GLASS, "&bReinforced Glass"), new ItemStack(Material.BLACK_WOOL), null, null, null});
        SlimefunItem.getByID("RUBBER_BOOTS").setRecipe(new ItemStack[] {null, null, null, rubber, null, rubber, rubber, null, rubber});
        SlimefunItem.getByID("NIGHT_VISION_GOGGLES").setRecipe(new ItemStack[] {new ItemStack(Material.COAL_BLOCK), new ItemStack(Material.COAL_BLOCK), new ItemStack(Material.COAL_BLOCK), new CustomItem(Material.GLASS, "&bReinforced Glass"), new ItemStack(Material.COAL_BLOCK), new CustomItem(Material.GLASS, "&bReinforced Glass"), new ItemStack(Material.COAL_BLOCK), null, new ItemStack(Material.COAL_BLOCK)});
        SlimefunItem.getByID("STEEL_PLATE").setRecipe(new ItemStack[] {null, null, null, null, SlimefunItem.getByID("STEEL_INGOT").getItem(), null, null, null, null});
        SlimefunItem.getByID("STEEL_PLATE").setRecipeType(pbType);
    }

    public static void changeCategories() {
        SlimefunItem.getByID("COPPER_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("TIN_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("ALUMINUM_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("LEAD_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("ZINC_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("MAGNESIUM_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("SILVER_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("REINFORCED_ALLOY_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("HARDENED_METAL_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("DAMASCUS_STEEL_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("STEEL_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("BRONZE_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("DURALUMIN_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("BILLON_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("BRASS_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("ALUMINUM_BRASS_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("ALUMINUM_BRONZE_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("CORINTHIAN_BRONZE_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("SOLDER_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("NICKEL_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("COBALT_INGOT").setCategory(Ingots);
        SlimefunItem.getByID("FERROSILICON").setCategory(Ingots);
        SlimefunItem.getByID("GILDED_IRON").setCategory(Ingots);
        SlimefunItem.getByID("REDSTONE_ALLOY").setCategory(Ingots);
        SlimefunItem.getByID("COPPER_DUST").setCategory(Dusts);
        SlimefunItem.getByID("TIN_DUST").setCategory(Dusts);
        SlimefunItem.getByID("ALUMINUM_DUST").setCategory(Dusts);
        SlimefunItem.getByID("LEAD_DUST").setCategory(Dusts);
        SlimefunItem.getByID("ZINC_DUST").setCategory(Dusts);
        SlimefunItem.getByID("MAGNESIUM_DUST").setCategory(Dusts);
        SlimefunItem.getByID("SILVER_DUST").setCategory(Dusts);
        SlimefunItem.getByID("IRON_DUST").setCategory(Dusts);
        SlimefunItem.getByID("GOLD_DUST").setCategory(Dusts);
        SlimefunItem.getByID("SULFATE").setCategory(Dusts);
        //SlimefunItem.getByID("REDSTONE").setCategory(Dusts);
        SlimefunItem.getByID("STEEL_PLATE").setCategory(Plates);
    }
}